### ISSUE TITLE
filter orderBy columns

### ISSUE THREAD

**Issue by mathroc** [graphile/graphile-build#110]
This is mostly a reminder for me to extend support of the `pgColumnFilter` to the `PgOrderAllColumnsPlugin`

Because there’s a few columns where it does not make sens to allow sorting (eg: uuid v4, json, maybe even text in some cases)

**Comment by benjie** [comment]
I did add it there:

https://github.com/graphile/graphile-build/blob/99e845a6100f6e1697dfaff8f50f0caa91daef61/packages/graphile-build-pg/src/plugins/PgOrderAllColumnsPlugin.js#L24

Does it need additional context?

**Comment by mathroc** [comment]
my bad, I missed it

and got it working with this filter : `if (isPgRowSortEnum && table && table.kind === "class") { // order by` (same as in the plugin). I wonder if that’s the right way to filter it though. if the filter is updated in the plugin I’ll have to find about it and update it. also, even if I know it will filter correctly for the plugin I’m targeting, it could also filter in another plugin that I might not want to filter on the same conditions. maybe we should add the plugin name in the context? that would be much easier

**Comment by benjie** [comment]
I’d rather we didn’t factor in the plugin name - that’s an implementation detail and we should be able to split, merge and rename plugins without affecting the output. The isPgRowSortEnum should be sufficient; if you added another plugin to re-add that column either it should ignore pgRowFilter or it should add extra Context so your pgRowFilter can be tweaked to differentiate.

**Comment by mathroc** [comment]
okay, I don’t now enough about the plugins internal so it’s a bit unclear at the moment, I guess it will need some documentation / examples once it’s stable
