### ISSUE TITLE
Use duck-typing on `pg` objects rather than instanceof

### ISSUE THREAD

**Issue by benjie** [graphile/graphile-build#114]
https://github.com/graphile/graphile-build/blob/f47ea82234434a48502ffd5b4c8069cca8ae4cfa/packages/graphile-build-pg/src/withPgClient.js#L17-L24

^ If there's more than one version of `pg` in the users node_modules then this causes things to be rejected with `"You must provide a valid PG client configuration"`

**Comment by benjie** [comment]
(If you hit this issue, the solution is to ensure you only have one version of `pg` installed in your node_modules folder. `yarn list` or `npm list` will help you see where the different versions are coming from - I advise piping them through `less`)

**Comment by benjie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Duck-type PG](https://trello.com/c/sSRD81cw/5-duck-type-pg)

**Comment by cdaringe** [comment]
ah, this just got me!

**Comment by cdaringe** [comment]
:tada:
