### ISSUE TITLE
NUMERIC function parameters:  Float! => String!

### ISSUE THREAD

**Issue by stlbucket** [graphile/graphile-build#127]
did numeric fields begin expressing as String! in the schema?   today i upgraded from 4.0.0-alpha2.24 to 4.0.0-alpha2.26 so that i could add this library:  https://github.com/mattbretl/postgraphile-plugin-connection-filter

at this point my graphQL mutations all now expect String! where previously they expected Float! when my function parameter type is NUMERIC.   

unfortunately, if I try to rollback to 2.24, the problem is still there, so it seems that maybe this postgraphile is not the problem.   

but maybe i had an old dependence or something?

**Comment by stlbucket** [comment]
![image](https://user-images.githubusercontent.com/2467892/33583140-b1e6867a-d90d-11e7-9848-9146816dc374.png)


I am not 100% sure if this is the line of code that sets this mapping, but makes sense.

**Comment by stlbucket** [comment]
instead, this is the line of code controlling this:

![image](https://user-images.githubusercontent.com/2467892/33583228-211ebee0-d90e-11e7-9a10-0a79e64a4dde.png)

**Comment by benjie** [comment]
Yes, please track postgraphql/postgraphql#506 for breaking change announcements during the alpha - I comment with every release that introduces breaking changes.

See also: https://github.com/graphile/graphile-build/pull/123
