### ISSUE TITLE
Custom Mutations Example

### ISSUE THREAD

**Issue by veebuv** [graphile/graphile-build#148]
Hey mate!

Apologies for setting this as an issue, but wanted to know if you could give us an example of a custom mutation and how we'd make it.

We love this plugin, used it for 3 startups now. But we've always had struggles/inconsistencies when building custom resolvers or methods.

The reason we want to do it, is because, in a basic way, want to add multiple rows into our PG database at one time

**Comment by chadfurman** [comment]
Hi friend, there are several examples in the postgraphile docs here: https://www.graphile.org/postgraphile/extending/

I don't see these items replicated in the graphile docs, but postgraphile is powered by graphile and so most things should be similar

**Comment by chadfurman** [comment]
You might be most interested in adding a mutation field: https://www.graphile.org/postgraphile/extending/#adding-root-querymutation-fields 

Let me know if you have more questions :)

**Comment by veebuv** [comment]
Hey @chadfurman thanks so much for the response!

Agreed that most things should be similar hence the question :)

I was referring to this page, apologies for not typing it in earlier - https://www.graphile.org/postgraphile/custom-mutations/

All we're looking for potentially is the example for the above link

**Comment by benjie** [comment]
Take a look at this forum example; in particular this custom mutation:

https://github.com/postgraphql/postgraphql/blob/master/examples/forum/TUTORIAL.md#registering-users

I’ve not moved it over to the graphile docs yet; thanks for the reminder 👍

**Comment by benjie** [comment]
That page now contains an example mutation and there's more example mutations here:

https://www.graphile.org/postgraphile/examples/

Cheers 👍
