### ISSUE TITLE
Support more complex conditions

### ISSUE THREAD

**Issue by tyvdh** [graphile/graphile-build#151]
Right now it's a very basic equals condition. Would really love to see $ne, $lt, $gt, $nin, $in, etc. added to the conditions support methods. Not sure how reasonable this is but if you could point me in the right direction of where to add this or a way to accomplish these methods that would be awesome.

**Comment by tyvdh** [comment]
Wrong repo. Sorry.

**Comment by benjie** [comment]
Okay; for anyone who finds this in the future though check out the community plugins

https://github.com/postgraphql/postgraphql/wiki/v4-plugins
