### ISSUE TITLE
type ENUM & values '*' cause crash

### ISSUE THREAD

**Issue by disarticulate** [graphile/graphile-build#153]
version: 0.1.0-alpha.38
REPRODUCTION:
```
DROP SCHEMA IF EXISTS test CASCADE;
CREATE SCHEMA test;

SET search_path = test, pg_catalog, public;

DROP TYPE IF EXISTS test_asterix;
CREATE TYPE test_asterix AS ENUM (
    '*'
);

DROP TABLE IF EXISTS test_asterix_table;
CREATE TABLE IF NOT EXISTS test_asterix_table (
	test_column test_asterix
)
```
error:
```
graphql_1   | Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
graphql_1   |     at assertValidSchema (/usr/local/lib/node_modules/postgraphql/node_modules/graphql/type/validate.js:78:11)
graphql_1   |     at Object.validate (/usr/local/lib/node_modules/postgraphql/node_modules/graphql/validation/validate.js:61:35)
graphql_1   |     at Object.<anonymous> (/usr/local/lib/node_modules/postgraphql/build/postgraphql/http/createPostGraphQLHttpRequestHandler.js:322:50)
graphql_1   |     at step (/usr/local/lib/node_modules/postgraphql/node_modules/tslib/tslib.js:133:27)
graphql_1   |     at Object.next (/usr/local/lib/node_modules/postgraphql/node_modules/tslib/tslib.js:114:57)
graphql_1   |     at fulfilled (/usr/local/lib/node_modules/postgraphql/node_modules/tslib/tslib.js:104:62)
graphql_1   |     at <anonymous>
graphql_1   |     at process._tickCallback (internal/process/next_tick.js:160:7)
```
Guessing the enum value '*' needs to be escaped.

**Comment by benjie** [comment]
PR to fix this would be welcome; perhaps by replacing * with _ASTERISK_ before inflection using a regexp (and also replacing double underscores with single in the result)

Check out enumName here:


https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/inflections.js

**Comment by disarticulate** [comment]
unfortunate, I can't really understand the entire process that goes into the inflection stuff.

Also note, the entire introspection fails, so even if this endpoint isn't critical, it takes everything down with it. Probably should have some type of bypass for these errors if a working endpoint fails.

**Comment by benjie** [comment]
> unfortunate, I can't really understand the entire process that goes into the inflection stuff.

Fortunately you don't need to - all you need to do is modify the `enumName` function here:

https://github.com/graphile/graphile-build/blob/d76180a34820440d320d7327f57d681bc28a0463/packages/graphile-build-pg/src/inflections.js#L63-L68

to do something like

```js
if (value === "") {
  return "_EMPTY_";
}
const valueSanitised = value.replace(/\*/g, '_ASTERISK_').replace(/__+/g, '_');
return value;
```

but a bit more intelligent regarding the underscores.

It'd be nice to test that with a few entries into the enums in the kitchen sink schema.

Code that produces something like this seems to me like a good idea:

```
* -> ASTERISK
** -> ASTERISK_ASTERISK
*** -> ASTERISK_ASTERISK_ASTERISK
foo* -> foo_ASTERISK
foo*_ -> foo_ASTERISK_
_foo* -> _foo_ASTERISK
*bar -> ASTERISK_bar
*bar_ -> ASTERISK_bar_
_*bar_ -> _ASTERISK_bar_
*baz* -> ASTERISK_baz_ASTERISK
```


> Also note, the entire introspection fails, so even if this endpoint isn't critical, it takes everything down with it. Probably should have some type of bypass for these errors if a working endpoint fails.


I disagree, it's better for the entire schema to fail so that you know something has gone wrong with your latest database migrations and can address the issue, rather than the system to attempt to limp along in a degraded state and you being none the wiser. These issues should be caught in the development or staging phases - well before they hit production.

**Comment by disarticulate** [comment]
i'll take a look. 

but for the last point: if you really want to fail everything, you'll need a better error reporting mechanism.  There's no identifying information in the error. I found it because I went through the entire schema commenting out various things.

**Comment by benjie** [comment]
I certainly don’t disagree with you there - errors need massive improvements! Unfortunately the one you hit here actually came from GraphQL itself, so it’s complex to figure out where it came from in your SQL. We’ll probably have to duplicate some of the GraphQL validations into our codebase which is annoying.

I wonder if the error above has more metadata on it that wasn’t output as part of the error message, e.g. the GraphQL path, that’d certainly improve the error messages significantly!
