### ISSUE TITLE
Error while loading Graphiql UI.

### ISSUE THREAD

**Issue by thekgt** [graphile/graphile-build#169]
Hi, 
We are trying out Postgraphile (It's great). But for schema, while opening the Graphiql UI, it gives following error: 

> Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "" does not.
    at assertValidSchema (/usr/lib/node_modules/postgraphile/node_modules/graphql/type/validate.js:78:11)
    at Object.validate (/usr/lib/node_modules/postgraphile/node_modules/graphql/validation/validate.js:61:35)
    at Object.<anonymous> (/usr/lib/node_modules/postgraphile/build/postgraphql/http/createPostGraphQLHttpRequestHandler.js:333:50)
    at step (/usr/lib/node_modules/postgraphile/node_modules/tslib/tslib.js:133:27)
    at Object.next (/usr/lib/node_modules/postgraphile/node_modules/tslib/tslib.js:114:57)
    at fulfilled (/usr/lib/node_modules/postgraphile/node_modules/tslib/tslib.js:104:62)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
1 error(s) in 100.27ms :: query IntrospectionQuery { __schema { queryType { name } mutationType { name } subscriptionType { name } types { ...FullType } directives { name description locations args { ...InputValue } } } } fragment FullType on __Type { kind name description fields(includeDeprecated: true) { name description args { ...InputValue } type { ...TypeRef } isDeprecated deprecationReason } inputFields { ...InputValue } interfaces { ...TypeRef } enumValues(includeDeprecated: true) { name description isDeprecated deprecationReason } possibleTypes { ...TypeRef } } fragment InputValue on __InputValue { name description type { ...TypeRef } defaultValue } fragment TypeRef on __Type { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name ofType { kind name } } } } } } } }

As far as I've studied, it is because GraphQL only allows keys starting with ASCII character or an underscore. So does that mean, schema that I am working on has some Type (or relation) with No Name?

Additional Info: Postgres 9.6.7
Extensions in the schema (Although I have tried on other schema with same set of Extensions): 
btree_gist         | 1.2     | public    
citext             | 1.3     | public    
dblink             | 1.2     | public    
hstore             | 1.4     | public    
intarray           | 1.2     | public    
ltree              | 1.1     | public    
pg_stat_statements | 1.4     | public    
pgcrypto           | 1.3     | public    
plpgsql            | 1.0     | pg_catalog
postgis            | 2.4.3   | public    
uuid-ossp          | 1.1     | public    

Any help is appreciated. Thanks.

**Comment by benjie** [comment]
Are you running the very latest postgraphile? I tried to improve some errors in it.

At the moment I can't tell you what's causing the issue other than the name of _something_ isn't matching that regexp after it is mangled by our inflection engine. It could be a type name, table name, column name, function name, enum value, or probably a few other things. I'd particularly look at your enums.

**Comment by thekgt** [comment]
Hi @benjie thanks for reverting. 
Yes, it is postgraphile 4.0.0-alpha2.31. I traced it down till graphql : assertValidName.js. I am afraid I can't tell you the Enums (for the sake of Confidentiality). But let me know if I can help you in any other way. 
Just asking, how does can there be something with no name?

**Comment by benjie** [comment]
It's due to the inflector mangling names:

https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/inflections.js

E.g. table `foo_bar_bazs` gets turned into model `FooBarBaz`. It also drops a lot of non-alphanumeric characters.

We can't do much to auto-detect this right now - it'd be super useful if GraphQL threw the errors earlier, but they don't do that until validation (after the schema has been constructed) and the errors don't hint at where within the schema it went wrong. A path to the bad element would be super helpful!

**Comment by benjie** [comment]
Look for anything that has a name that doesn't contain at least one alphanumeric (latin alphabet) character.

**Comment by thekgt** [comment]
I took the dump of my schema, and searched for non-ascii character, there were a couple, that too in comments, removed them, ran postgraphile again, No luck.

**Comment by benjie** [comment]
The issue is more likely to be that the characters are being stripped; e.g. prior to Saturday asterisks would be removed from enums. Look for things that have short names where the names have symbols or other non-alphanumeric characters. I think enums are a likely place for this to be an issue, but it could be anywhere. Without seeing your schema I can't help you track it down.

**Comment by thekgt** [comment]
Okay @benjie . Let me try for some more time. 
Thanks for your response. Appreciate it.

**Comment by thekgt** [comment]
Hi @benjie : I found out an enum which was creating the problem: 

> CREATE TYPE operator_compare AS ENUM (
    '>',
    '>=',
    '=',
    '!=',
    '<=',
    '<'
);

I dropped this enum and it worked. 
Could you please give us more insight on  this. Is there any way we can avoid this?

**Comment by benjie** [comment]
GraphQL wants enums to be alphanumeric; so those could be named instead:

- GREATER_THAN
- GREATER_THAN_OR_EQUAL
- EQUAL
- NOT_EQUAL
- LESS_THAN_OR_EQUAL
- LESS_THAN

I might add these to the list of overrides actually: 

https://github.com/graphile/graphile-build/blob/5e2e6979a1ea413350b5d22b17286b56f1b19825/packages/graphile-build-pg/src/inflections.js#L92-L101

**Comment by thekgt** [comment]
Yes, you spoke my mind, I was about to suggest something like that. Thanks this helps.

**Comment by benjie** [comment]
Broadened support here: https://github.com/graphile/graphile-build/pull/171/files#diff-a327206bffe96dce6fa0c75f71f3afe7R113
