### ISSUE TITLE
Smart comments: option to skip a table

### ISSUE THREAD

**Issue by benjie** [graphile/graphile-build#186]
e.g. if you've created a table instead of a type so that you can return that type from a function and still have relations supported (but you'll never actually store data to that table) then it doesn't make sense to add the various queries/mutations to your schema. Adding a `@skip` or `@hidden` tag would be a very convenient way of managing this.

**Comment by hmaurer** [comment]
Close @benjie ?

**Comment by benjie** [comment]
Possible vis smart comments: https://www.graphile.org/postgraphile/smart-comments/
