### ISSUE TITLE
Custom query format (not GraphQL). Is it possible?

### ISSUE THREAD

**Issue by KleinMaximus** [graphile/graphile-build#191]
Is it possible to use graphile-builder without graphql query, but with some other syntax?
For example, to create some plugin that will convert my JSON-request format to the desired form?

**Comment by benjie** [comment]
graphile-build's purpose is to build a GraphQL schema. I don't quite understand what use case you're asking for, but if it's outside the scope of GraphQL it's outside the scope of the project.

Perhaps you could expand with exactly what you want to do (maybe with some pseudocode) and we could give some pointers?
