### ISSUE TITLE
args not in the correct order

### ISSUE THREAD

**Issue by iamgmd** [graphile/graphile-build#232]
I have the following query:

```
{
  contact_all(where: {
    t4a_title_name_in: ["Miss","Dr"]
    gendercode_name: "Female"
    createdby_ref: {
      fullname: "A, User"
    }
    OR: {
      createdby_ref: {
      fullname: "B, User"
    	}
    }
  },orderBy:[lastname_ASC],limit:10) {
    contactid
    t4a_title_name
    firstname
    lastname
    gendercode_name
    createdby_ref {
      systemuserid
      fullname
    }
    modifiedby_ref {
      systemuserid
      fullname
    }
  }
}
```

Running parseResolveInfo(info), I get the following output:

```
{ name: 'contact_all',
  alias: 'contact_all',
  args:
   { where:
      { OR: [Array],
        gendercode_name: 'Female',
        t4a_title_name_in: [Array],
        createdby_ref: [Object] },
     orderBy: [ 'lastname_ASC' ],
     limit: 10 },
  fieldsByTypeName:
   { Contact:
      { contactid: [Object],
        t4a_title_name: [Object],
        firstname: [Object],
        lastname: [Object],
        gendercode_name: [Object],
        createdby_ref: [Object],
        modifiedby_ref: [Object] } } }
```

As you can see the args.where is not in the same order as inputted on the graphql query, this makes it unusable when using this utility to generate T-SQL manually in the resolver.

Is there a fix or workaround?

**Comment by benjie** [comment]
I don’t think GraphQL objects are intended to be treated as ordered - they’re just hashes/dictionaries.

I believe this is the relevant code:

```
const args = getArgumentValues(field, val, variableValues) || {};
```

I.e. we call in to GraphQL.js for parsing the arguments. If you can confirm that GraphQL.js exhibits the same issue then please redirect your question there as I do not want to fork from the reference implementation.

**Comment by benjie** [comment]
Taking a guess, I think what you mean by:

```
where: {
    t4a_title_name_in: ["Miss","Dr"]
    gendercode_name: "Female"
    createdby_ref: {
      fullname: "A, User"
    }
    OR: {
      createdby_ref: {
      fullname: "B, User"
    	}
    }
  }
```

Is effectively (pseudocode):
```
(
  (t4a_title_name_in: ["Miss","Dr"])
AND 
  (gendercode_name: "Female")
AND
  (
    (createdby_ref: {fullname: "A, User"})
  OR
    (createdby_ref: {fullname: "B, User"})
  )
)
```

Have I got your intent right? If so, I'd model it slightly differently:

```
where: {
    t4a_title_name_in: ["Miss","Dr"]
    gendercode_name: "Female"
    OR: [
      {createdby_ref: {
        fullname: "A, User"
      }},
      {createdby_ref: {
        fullname: "B, User"
      }}
    ]
  }
```

This makes it explicit what the options in the "OR" are (rather than using their position to implicitly indicate that) and it can also easily nest, e.g. `(A and B and (C or (D and E))`. 

Take a look at [this plugin](https://github.com/graphile-contrib/postgraphile-plugin-connection-filter#examples) for some inspiration - I think you can follow this approach with a few simple changes.

**Comment by benjie** [comment]
Since this is not something Graphile itself can address (it's defined in graphql-js) I'm going to close it.
