### ISSUE TITLE
Error: Cannot find module 'lru-cache'

### ISSUE THREAD

**Issue by rongfengliang** [graphile/graphile-build#245]
when i  use yarn insatll graphile-build ` npm install --save graphile-build graphql` 
it throws error .  only if  i  install   lru-cache  maybe some dependency loss in  graphile-build  package
module.js:538
    throw err;
    ^

Error: Cannot find module 'lru-cache'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/dalong/mylearning/postgraphql/first/node_modules/graphile-build/node8plus/makeNewBuild.js:22:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by benjie** [comment]
Good catch; thanks! This is one risk of the monorepo approach: never sure if you have all your deps defined in the right places.

**Comment by rongfengliang** [comment]
@benjie  
my code is copy from docs 
[getting-started](https://www.graphile.org/graphile-build/getting-started/)
```code
const { buildSchema, defaultPlugins } = require("graphile-build");
const { printSchema } = require("graphql/utilities");

buildSchema(defaultPlugins).then(schema => {
  console.log(printSchema(schema));
});
```
and package.json
```json
{
  "name": "first",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "graphile-build": "^4.0.0-rc.3",
    "graphql": "^0.13.2"
  },
  "scripts": {
    "b": "node build"
  }
}
```
only if  i add lru-cache 
```code 
{
  "name": "first",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "graphile-build": "^4.0.0-rc.3",
    "graphql": "^0.13.2",
    "lru-cache": "^4.1.3"
  },
  "scripts": {
    "b": "node build"
  }
}
```
it works 
so i think it maybe have some package deps is not included in the graphile-build

**Comment by benjie** [comment]
Yes, I agree - good catch 👍
