### ISSUE TITLE
Use better error message for invalid plugin

### ISSUE THREAD

**Issue by vjpr** [graphile/graphile-build#257]
I had this code:

```
    appendPlugins: [
      isDev ? PostGraphileConnectionFilterPlugin : null
    ],
```

This is the error

```
Error: Option 'appendPlugins' should be an array of functions, found 'object' at index 0
    at ensureValidPlugins (/xxx/node_modules/.registry.npmjs.org/postgraphile-core/4.0.0-rc.4/graphql@0.12.3+pg@7.4.3/node_modules/postgraphile-core/src/index.js:20:13)
```

This is the fix:

```
    appendPlugins: [
      isDev ? PostGraphileConnectionFilterPlugin : null
    ].filter(Boolean),
```

But it would be nice to have a better error message to tell if something is null or undefined.

**Comment by benjie** [comment]
Ah yes; I'm clearly using `typeof`. TBH we should probably just skip nulls when processing. PR welcome 👍

**Comment by vjpr** [comment]
An argument for leaving nulls is when you don't export your plugin
correctly (or there is some babel issue), and you can't tell why its not
loading.

**Comment by benjie** [comment]
That's a good point 👍
