### ISSUE TITLE
Using JWT claims in makeExtendSchemaPlugin plugin.

### ISSUE THREAD

**Issue by hyperparsa** [graphile/graphile-build#266]
I'm using makeExtendSchemaPlugin to add new resolvers, but in some of them I need to use jwt claims.

Right now I use context.pgRole to determine if the request was logged in and then query postgresql for the jwt claims.

Is there a better way?

**Comment by benjie** [comment]
Adding the jwt claims to context seems like a good idea; I’d be happy to rev

**Comment by benjie** [comment]
Fat fingers on mobile!

**Comment by benjie** [comment]
Adding the jwt claims to context seems like a good idea; I’d be happy to review a PR adding that. In the meantime you can use `additionalGraphQLContextFromRequest` assuming you’re using the library version to add any additional information you need to context (e.g. by parsing request headers).

**Comment by hyperparsa** [comment]
@benjie I just tried that and It worked perfectly, Thank you!
As for PR I can't really wrap my head around the whole plugin architecture, don't know where to go from there.
As always great work on the project.

**Comment by hyperparsa** [comment]
I did it!
I went the simplest route and just returned jwtClaims as that was coincidentally the same name I was using in my own code. 

also slightly unrelated: I had issues running scripts/dev because of "node: bad option --ignore", had to remove that part from the scripts, couldn't find any info on the internet.
