### ISSUE TITLE
Switch Point type from { x, y } back to String

### ISSUE THREAD

**Issue by saerdnaer** [graphile/graphile-build#267]
Question: Is there an easy way to create a Plugin to modify the behaviour of https://github.com/graphile/graphile-build/blob/be71fd4d7153cfe384770fe6268b5ec736657f05/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js to export Points as String "(x,y)" like v3 did, and not as Object {x, y} with Attributes x and y?

**Comment by benjie** [comment]
That should be fairly easy; I doubt this will work first time as I'm writing it straight into GitHub editor, but something like this:

```js
module.exports = function PgPointStringPlugin(builder) {
  builder.hook('build', (build) => {
    build.pgRegisterGqlTypeByTypeId(600, () => GraphQLString);
    build.pgRegisterGqlInputTypeByTypeId(600, () => GraphQLString);
    delete pg2GqlMapper[600]; // Hack... sorry!
    return build;
  });
}
```

**Comment by benjie** [comment]
Oops, missed `build.*` on a bunch of these vars. Fixed. Did it work?

**Comment by benjie** [comment]
I'm closing this to keep things manageable; feel free to re-open 👍

**Comment by saerdnaer** [comment]
Will test again on Monday ;-)

**Comment by saerdnaer** [comment]
eslint complains with `Assignment to property of function parameter 'build'. (no-param-reassign)` on ` delete build.pg2GqlMapper[600];`, asside from that everything looks fine for now.

**Comment by benjie** [comment]
Great! Yeah; I noted that line was a hack, just `// eslint-disable-line` it 😁
