### ISSUE TITLE
Error with results of hashFieldAlias

### ISSUE THREAD

**Issue by farant** [graphile/graphile-build#268]
Getting the error:
```
Disallowed alias '@@3308e66eced24f113896497e3a487e8f6cf810ba'
```
when accessing a very long field name. 

Error seems to be on line 189...190 of `QueryBuilder.js`

I see the regex is `/^@*[_A-Za-z][_0-9A-Za-z]*$/` which disallows numerals as the initial character after optional `@` characters. I would suggest one of:

* Changing this to allow numerals in the initial position (not sure if there is a security/other concern)
* updating `makeNewBuild.js` line 90 to something like this:
```
 return `@@_${hashFieldAlias(alias)}`;
```
(added an underscore after the two @ symbols)
* Update `hashFieldAlias` in `makeNewBuild.js` to prepend a letter or underscore or letter to the generated hash it stores.

I know I was one of the test cases for this. Sorry I didn't catch it sooner!

**Comment by benjie** [comment]
Huh! Good catch!
