### ISSUE TITLE
Classification has already been registered

### ISSUE THREAD

**Issue by g-borgulya** [graphile/graphile-build#291]
Hi,
Background:
we've been using postgraphql 3.5.4 for a complex database. It works well. As we need to extend our schema, I decided to do that with `appendPlugins`, so I switched to postgraphile 4.0.0-rc.4. (It uses graphile-utils 4.0.0-rc.9, which uses graphql 0.13.2.)

Problem:
If I run the same configuration (even without the appendPlugins) then I get this message at postgraphile initialization:
`Error: Type 'Classification' has already been registered!`
at `.../node_modules/graphile-build/src/makeNewBuild.js:741:17`

The options I use for postgraphile are:
```
      graphiql: true,
      watchPg: true,
      enableCors: true,
      jwtPgTypeIdentifier: '...'
      jwtSecret: '...'
      pgDefaultRole: '...'
```

The interesting thing is that I couldn't find anything called `Classification` in the database schema or anywhere in the code. There's no table/view/function anything with this name. How can I fix this then?

**Comment by g-borgulya** [comment]
Thank you for your fast response, @benjie 

So we checked all our schema but we don't find anything there with the suggested names. Actually if I list the whole schema there's nothing in it starting with `classi` case-insensitive. So I suspect that even if there should be a problem with our schema, the name `Classification` can't be correct.

I hope we can figure this out without having to share the 5000+ lines of our schema definition.

**Comment by benjie** [comment]
Are you positive it’s connecting to the correct DB? Try connecting it to a different, clean DB, and see what happens then. Also try the CLI version to see if it produces the same issue.

**Comment by g-borgulya** [comment]
Thank you a lot @benjie for your help.

The problem is on our side: the database I was trying to connect to had the wrong schema, and it actually did have a type called `classification` - at least we know that. Sorry for the false alarm.

**Comment by benjie** [comment]
No problem; I'm currently working on making these error message a lot more explicit. Here's a preview:

![screenshot 2018-08-29 14 26 39](https://user-images.githubusercontent.com/129910/44790608-a87d5e80-ab97-11e8-826e-d3b12997417b.png)

**Comment by g-borgulya** [comment]
That looks very helpful!

**Comment by benjie** [comment]
Closing this as this should be much easier to debug when the next release goes out: https://github.com/graphile/graphile-build/pull/292
