### ISSUE TITLE
[graphile-build-pg] Can't return setof composite type from procedure

### ISSUE THREAD

**Issue by SomeHats** [graphile/graphile-build#60]
A procedure can't return a setof some composite type at the moment.

Trying to start postgraphile with this schema:
```sql
create schema test;
create type test.some_type as (a int, b int);
create function test.do_something()
  returns setof test.some_type
  as $$ select 1, 2; $$
  language sql stable;
```

Gives this error:
```
Error: Do not have a connection type 'SomeTypesConnection' for 'SomeType' so cannot create procedure field
```

---

Postgraphile + graphile-build are looking awesome - thank you so much for your amazing work on them! ✨

**Comment by benjie** [comment]
Fix is out in `postgraphql@next` - thanks for reporting 👍
