### ISSUE TITLE
override keys with PgForwardRelationPlugin

### ISSUE THREAD

**Issue by mathroc** [graphile/graphile-build#65]
Hi,

I’m trying to override a key with it’s single relation, for that I’ve, overridden the inflector like this:

```js
defaultInflection.singleRelationByKeys = ([{column}]) => column;
```

but I have this error:

> Error: Overwriting key '…' is not allowed!

I’d like to override to avoid having, for example, both `owner` and `accountByOwner` and instead just have `owner` resolve to the `Account` type. 
So my question is, is `extend` complaining because it can’t override a key? or because it thinks it’s probably an error?

If the error is just to prevent accidental overriding, I could duplicate and adapt `PgForwardRelationPlugin` but it’ll make it harder to maintain it in the future

maybe I can avoid overriding those fields by not adding them or removing them, but it will probably mean at duplicating some logic form `PgForwardRelationPlugin` into a new plugin (if I can add a plugin before `PgForwardRelationPlugin` that would remove those fields) or duplicating the plugin that add the fields and make it more complex and hard to maintain too

do you have suggestion on how to approach that ? would you be open to a PR that adds an option to `PgForwardRelationPlugin` so that it overrides the keys instead of calling the inflector ?

**Comment by benjie** [comment]
"extend" deliberately throws if you try and overwrite a key - this is to avoid surprises. If you want to overwrite you can use Object.assign instead; however as you say this won't help as you have to fork the plugin.

Instead I'd fork the columns plugin and simply not add the column as a field in the first place. You could add a different plugin (make sure it comes before the relations plugin but after the columns plugin) that deletes the "owner" column, but be aware that this will not remove the look-ahead helper for that field name and thus the "owner" column value will be fetched from the DB unnecessarily. This should be fairly harmless for this case, I only raise it in case others read this and apply it to a different issue :)

I would not accept the PR that you propose, however I would consider a PR that allows the user to somehow filter the columns made available in the first place. However I'm not best sure the form this should take. It would be excellent if a similar filter could be applied to the input types for the table also - I have use cases for this! Please propose something before doing the work, I'm sure we can figure out a good solution 👍

**Comment by mathroc** [comment]
thx, for the detaild answer, extending the "columns" plugins seems a good solution. what about adding an optional `pgAddColumn` filter callback to the plugin that defaults to `(introspectionResultsByKind, attr) => true`

and add `.filter(pgAddColumn.bind(null, introspectionResultsByKind))` just after https://github.com/graphile/graphile-build/blob/f47ea82/packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js#L41

then in the `pgAddColumn` I give I could check whether the column with something like:

```js
return introspectionResultsByKind.constraint
    .filter(con => con.type === "f")
    .filter(con => con.classId === attr.classId)
    .filter(con => con.keyAttributeNums.length === 1)
    .filter(con => con.keyAttributeNums[0] === attr.num).length === 0;
```

the same strategy could be applied to the input columns too. probably just with 2 different callbacks

Do this looks like it could works ?

**Comment by benjie** [comment]
Something like this sounds reasonable 👍 

So I'm thinking something like:

```js
pgColumnFilter(attr, build, context)
```

Where:

- `attr` is the same as in the code - i.e. the attribute details for the current column
- `build` is the [build object](https://www.graphile.org/graphile-build/hooks/#build-object-build) (in case you need reference to `pgIntrospectionResultsByKind` or `pgGqlTypeByTypeId` or whatever)
- `context` is the [context object](https://www.graphile.org/graphile-build/hooks/#context-object-context) (which contains `scope.isPgPatch` which is useful for dropping things from patch; but I can (and should) also add `type: "GraphQLInputObjectType"` or similar to it so you can see if it's an input or not)

(I'm deliberately not adding `table` here because it can be derived from `attr` and `build` if it's not already available on `attr` directly (which I think it might be).)
