### ISSUE TITLE
Mention `yarn add postgraphile` here (or npm or npx or...)

### ISSUE THREAD

**Issue by chadfurman** [graphile/graphile-build#66]
Basically, update install instructions for postgraphile -- or link to them.  Right now we only like to postgraphile-core which does not mention the install instructions here: https://www.graphile.org/postgraphile/introduction/

**Comment by benjie** [comment]
I plan to move PostGraphQL (as PostGraphile) into the `graphile` organization when we release v4; but we should probably add something to the README redirecting people who are after postgraphile to the relevant repo 👍
