### ISSUE TITLE
Buffer error at install

### ISSUE THREAD

**Issue by qpautrat** [graphile/graphile-build#68]
Hi there,

I am facing an issue at install process with `npm`.

`npm ERR! Buffer.alloc is not a function`

npm version: `5.4.1`
node version: `5.4.0`
pgsql version: `9.3`

Thanks.

**Comment by benjie** [comment]
Hey @qpautrat thanks for reporting this; can you please provide a full stack trace? `graphile-build` successfully installs in Node 4.3.2 and v8+ so I'm not sure why 5.4.0 would give any issues...

https://travis-ci.org/postgraphql/postgraphql/jobs/274567516

**Comment by benjie** [comment]
Please note that we do not support PostgreSQL versions before 9.4 (though this error sounds like it's coming from some Node code rather than PG).

**Comment by qpautrat** [comment]
Hey @benjie 

I would not open an issue if I thought it was an issue related to pgsql of course. 
My bad, I didn't read the log file completely. There it is the trace I get:

```
TypeError: Buffer.alloc is not a function
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/pack.js:32:20)
4 verbose stack     at Module._compile (module.js:398:26)
4 verbose stack     at Object.Module._extensions..js (module.js:405:10)
4 verbose stack     at Module.load (module.js:344:32)
4 verbose stack     at Function.Module._load (module.js:301:12)
4 verbose stack     at Module.require (module.js:354:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/lib/create.js:6:14)
4 verbose stack     at Module._compile (module.js:398:26)
4 verbose stack     at Object.Module._extensions..js (module.js:405:10)
4 verbose stack     at Module.load (module.js:344:32)
4 verbose stack     at Function.Module._load (module.js:301:12)
4 verbose stack     at Module.require (module.js:354:17)
4 verbose stack     at require (internal/module.js:12:17)
4 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/tar/index.js:4:30)
4 verbose stack     at Module._compile (module.js:398:26)
```

**Comment by chadfurman** [comment]
This looks like an issue in your NPM packages.  Are you able to upgrade/downgrade to Node LTS?  older versions of node aren't supported, even by NodeJS:

https://github.com/nodejs/LTS

**Comment by chadfurman** [comment]
I suggest closing this issue.  Node 5.4 is not in active maintenance, and this is apparently an error in the node modules associated with that version.

**Comment by qpautrat** [comment]
@chadfurman You are absolutely right.
I updated to node 8.4.0 and it is good 👍 
I'm sorry I'm not used to node world, didn't I was that late.

Anyway thanks !
