### ISSUE TITLE
Functions with arguments that are arrays of custom types are not parsed correctly

### ISSUE THREAD

**Issue by cookejames** [graphile/graphile-build#83]
Here there are two arguments `newPostContents` and `schedulesWithOptimal` that are arrays of a custom types however they are shown as type `string`. Custom types that aren't arrays such as `interactionType` are interpreted correctly.

Do you have any suggestion where to start looking at the schema parsing code to fix this?
<img width="363" alt="mutation" src="https://user-images.githubusercontent.com/2211370/30874670-f6fa0a44-a2e8-11e7-88a5-4dc3e150fd9a.png">
<img width="755" alt="function" src="https://user-images.githubusercontent.com/2211370/30874687-ff43a138-a2e8-11e7-81ba-44a571654ba4.png">

**Comment by benjie** [comment]
Can you provide a minimal pg_dump that reproduces this?

The issue most likely exists in this file, in that we cannot find or build a GraphQL type to match the PostgreSQL one:

https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/plugins/PgTypesPlugin.js

**Comment by benjie** [comment]
See also ReturnType in this file:

https://github.com/graphile/graphile-build/blob/master/packages/graphile-build-pg/src/plugins/PgColumnsPlugin.js

**Comment by cookejames** [comment]
Thanks I will try and get a minimal dump that reproduces the problem and have a look at those files

**Comment by cookejames** [comment]
This should be enough to reproduce the error with the createScheduledPost mutation
[minimaltables.txt](https://github.com/graphile/graphile-build/files/1334668/minimaltables.txt)

**Comment by benjie** [comment]
```
[issue83] # \df
List of functions
-[ RECORD 1 ]-------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Schema              | public
Name                | create_scheduled_post
Result data type    | posts
Argument data types | campaign_id uuid, new_post_contents new_post_content[], interaction_type interaction_types, schedule_datetimes character varying[], schedules_with_optimal schedules_with_optimal[], media_ids character varying[], approval_state approval_states DEFAULT 'published'::approval_states
Type                | normal
```

We can rule out https://github.com/postgraphql/postgraphql/issues/580 at least; so that's good news!

```
[issue83] # select * from pg_type where typname like '%schedules_with_opt%';
-[ RECORD 1 ]--+------------------------
typname        | schedules_with_optimal
typnamespace   | 2200
typowner       | 10
typlen         | -1
typbyval       | f
typtype        | c
typcategory    | C
typispreferred | f
typisdefined   | t
typdelim       | ,
typrelid       | 7566694
typelem        | 0
typarray       | 7566695
typinput       | record_in
typoutput      | record_out
typreceive     | record_recv
typsend        | record_send
typmodin       | -
typmodout      | -
typanalyze     | -
typalign       | d
typstorage     | x
typnotnull     | f
typbasetype    | 0
typtypmod      | -1
typndims       | 0
typcollation   | 0
typdefaultbin  | ¤
typdefault     | ¤
typacl         | ¤
-[ RECORD 2 ]--+------------------------
typname        | _schedules_with_optimal
typnamespace   | 2200
typowner       | 10
typlen         | -1
typbyval       | f
typtype        | b
typcategory    | A
typispreferred | f
typisdefined   | t
typdelim       | ,
typrelid       | 0
typelem        | 7566696
typarray       | 0
typinput       | array_in
typoutput      | array_out
typreceive     | array_recv
typsend        | array_send
typmodin       | -
typmodout      | -
typanalyze     | array_typanalyze
typalign       | d
typstorage     | x
typnotnull     | f
typbasetype    | 0
typtypmod      | -1
typndims       | 0
typcollation   | 0
typdefaultbin  | ¤
typdefault     | ¤
typacl         | ¤

Time: 0.903 ms
```

So both the array type and the non-array type are present and introspectable. I'm going to flag this as a bug and look into it when I get a chance 👍

**Comment by cookejames** [comment]
Thanks will have a look at it later myself as well

**Comment by benjie** [comment]
If you use Node 8.5 then you can stick a `debugger` statement in the plugin and use `node --inspect` to see exactly what's going on. This is especially useful if you manage to reproduce it via a `postgraphile-core` test (these exercise most of the stack currently) - that way you can limit it to running just that one test (via `test.only` or similar approaches) and figure out exactly what's going on.

**Comment by benjie** [comment]
Working on this currently. Almost have it sorted.

**Comment by benjie** [comment]
Well... I have it sorted if the table and the columns and the types are all defined in one of the schemas you're exporting. If not it gets a little more... interesting.

Currently looking into adding recursive CTEs into our introspection query 😳

**Comment by benjie** [comment]
Work in progress is here. I've not pushed the recursive query yet as it's not working.

https://github.com/graphile/graphile-build/pull/92

**Comment by benjie** [comment]
@cookejames Sorry about the delay on this! I think it's fixed now, just waiting for tests to pass.

**Comment by Qweritos** [comment]
I have a similar problem, but with subtype of range type: 
```sql
CREATE TYPE app.foo AS RANGE (subtype = float8, subtype_diff = float8mi);

CREATE FUNCTION app.set_employee_schedule_for_day(array_of_foo app.foo[])
/* ... */
```
So, `arrayOfFoo` argument have a type `String`.

postgraphile: "4.0.0-beta.10"

**Comment by Qweritos** [comment]
I have a similar problem, but with subtype of range type: 
```sql
CREATE TYPE app.foo AS RANGE (subtype = float8, subtype_diff = float8mi);

CREATE FUNCTION app.set_employee_schedule_for_day(array_of_foo app.foo[])
/* ... */
```
So, `arrayOfFoo` argument have a type `String`.

postgraphile: "4.0.0-beta.10"

**Comment by benjie** [comment]
Please file as a fresh issue 👍
